#ifndef _STARX_ERROR___INC_H_
#define _STARX_ERROR___INC_H_

#define ERROR_STARX_SUCCESSFUL						0
#define ERROR_STARX_NOT_INITIALIZED					-1
#define ERROR_STARX_ALREADY_INITIALIZED				-2
#define ERROR_STARX_TIME_OUT							-3
#define ERROR_STARX_INVALID_ID						-4
#define ERROR_STARX_INVALID_PARAMETER				-5
#define ERROR_STARX_DEVICE_NOT_ONLINE				-6
#define ERROR_STARX_FAIL_TO_RESOLVE_NAME				-7
#define ERROR_STARX_INVALID_PREFIX					-8
#define ERROR_STARX_ID_OUT_OF_DATE					-9
#define ERROR_STARX_NO_RELAY_SERVER_AVAILABLE		-10
#define ERROR_STARX_INVALID_SESSION_HANDLE			-11
#define ERROR_STARX_SESSION_CLOSED_REMOTE			-12
#define ERROR_STARX_SESSION_CLOSED_TIMEOUT			-13
#define ERROR_STARX_SESSION_CLOSED_CALLED			-14
#define ERROR_STARX_REMOTE_SITE_BUFFER_FULL			-15
#define ERROR_STARX_USER_LISTEN_BREAK				-16
#define ERROR_STARX_MAX_SESSION						-17
#define ERROR_STARX_UDP_PORT_BIND_FAILED				-18
#define ERROR_STARX_USER_CONNECT_BREAK				-19
#define ERROR_STARX_SESSION_CLOSED_INSUFFICIENT_MEMORY	-20
#define ERROR_STARX_INVALID_APILICENSE				-21

#endif //// #ifndef _STARX_ERROR___INC_H_